INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('CHI98', 'Soldier Field', 'CHI', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('SEA00', 'Lumen Field', 'SEA', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('WAS00', 'FedExField', 'WAS', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('BAL00', 'M&T Bank Stadium', 'BAL', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('CAR00', 'Bank of America Stadium', 'CAR', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('IND00', 'Lucas Oil Stadium', 'IND', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('GNB00', 'Lambeau Field', 'GNB', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('NOR00', 'Mercedes-Benz Superdome', 'NOR', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('MIA00', 'Hard Rock Stadium', 'MIA', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('CIN00', 'Paycor Stadium', 'CIN', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('DET00', 'Ford Field', 'DET', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('TAM00', 'Raymond James Stadium', 'TAM', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('NAS00', 'Nissan Stadium', 'NAS', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('JAX00', 'TIAA Bank Stadium', 'JAX', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('LAX01', 'SoFi Stadium', 'LAX', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('BOS00', 'Gillette Stadium', 'BOS', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('ATL97', 'Mercedes-Benz Stadium', 'ATL', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('KAN00', 'GEHA Field at Arrowhead Stadium', 'KAN', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('MIN01', 'U.S. Bank Stadium', 'MIN', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('DAL00', 'AT&T Stadium', 'DAL', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('PHI00', 'Lincoln Financial Field', 'PHI', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('SFO01', 'Levi''s Stadium', 'SFO', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('HOU00', 'NRG Stadium', 'HOU', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('PIT00', 'Acrisure Stadium', 'PIT', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('CLE00', 'FirstEnergy Stadium', 'CLE', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('BUF00', 'New Era Field', 'BUF', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('DEN00', 'Empower Field at Mile High', 'DEN', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('VEG00', 'Allegiant Stadium', 'VEG', 'dome');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('NYC01', 'MetLife Stadium', 'NYC', 'open');
INSERT INTO stadium_details (stadium_id, stadium_name, home_team, type) VALUES ('PHO00', 'State Farm Stadium', 'PHO', 'dome');